//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDaveBartonAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestDaveBartonAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZiXqebE8QBWPZjEWwMTSY1wSkp0Rsx2FvLClGI+8/ms=.
        /// </summary>
        internal static string AESKey {
            get {
                return ResourceManager.GetString("AESKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to patZP179FsgSX9kcs.c186bc3a2d6d37691df2bdac63646b3c30488765d441db73067cce9127ccb5b0.
        /// </summary>
        internal static string AirTableAppKey {
            get {
                return ResourceManager.GetString("AirTableAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app7wKihKHMPmcDF1.
        /// </summary>
        internal static string AirTableBaseId {
            get {
                return ResourceManager.GetString("AirTableBaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Sidney\Google Drive\BPM Software Solutions\Clients\Claim Choice\Dave Barton\Data\output\Airtable_Records.csv.
        /// </summary>
        internal static string AirtableCSVOutputFilePath {
            get {
                return ResourceManager.GetString("AirtableCSVOutputFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tblaX2a86MZnjJwLg.
        /// </summary>
        internal static string AirTableTableId {
            get {
                return ResourceManager.GetString("AirTableTableId", resourceCulture);
            }
        }
    }
}
